# Basic Config
esphome:
  name: ${device_name}
  comment: ${device_description}

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true # Don't do a full scan, connect immediately

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret fallbackpass

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    id: my_ota
    password: !secret otapass   

# Disable web server to save memory and reduce unexpected crashes and resets
# web_server:
#   version: 3
#   port: 80
#   auth:
#     username: !secret otauser
#     password: !secret otapass

# Disable logging to save memory and reduce unexpected crashes and resets
# logger:
#   baud_rate: 0 # (UART logging interferes with cse7766)
#   logs:
#     sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    icon: mdi:power-standby
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"
    icon: mdi:power-standby

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_name}_wifi_signal"
    update_interval: 60s
    icon: mdi:broadcast
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_name}_uptime"
    update_interval: 60s
    icon: mdi:timer-outline
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "${friendly_name} Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "${friendly_name} Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "${friendly_name} Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "${friendly_name} Daily Energy"
    icon: mdi:lightning-bolt-circle
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    icon: mdi:power-socket-us
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True

button:
  - platform: restart
    name: "Restart ${friendly_name}"
    icon: mdi:restart

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_name}_esphome_version"
    icon: mdi:numeric
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      icon: mdi:ip-network
    ssid:
      name: ${friendly_name} Connected SSID
      icon: mdi:wifi-star
    mac_address:
      name: ${friendly_name} Mac Wifi Address
      icon: mdi:router-network-wireless