<<: !include sonoff_plug_common.yaml

substitutions:
  device_name: sf1
  device_description: Sonoff S31 Plug | Stereo and Speakers Power Control
  friendly_name: Speakers
  ip_address: 192.168.0.105
  gateway: 192.168.0.1
  subnet: 255.255.255.0